### ISSUE TITLE
TAG列表的行名翻译解决方案

### ISSUE THREAD

**Issue by xioxin** [Mapaler/EhTagTranslator#10]
我通过字体的方式解决了行名翻译问题
效果如下
![image](https://cloud.githubusercontent.com/assets/5716100/15628338/3091df20-2531-11e6-98ca-8ff8fd5b4a68.png)
方法是使用字体的视觉连字的特性 将英文字母替换为中文
![image](https://cloud.githubusercontent.com/assets/5716100/15628354/880c8b38-2531-11e6-8320-068acdd47c72.png)

代码：(拷贝到通用样式即可)

``` css
@font-face {
    font-family: 'extranslate';
    src: url(data:font/truetype;charset=utf-8;base64,d09GRgABAAAAAA89AA8AAAAAE7gAAQAAAAAAAAAAAAAAAAAAAAAPKAAAABVEU0lHAAAOFAAAAAgAAAAIAAAAAUdERUYAAA4cAAAAFwAAABgAPgADR1BPUwAADjQAAAAgAAAAIER2THVHU1VCAAAOVAAAANMAAAE8tw66109TLzIAAAHEAAAATAAAAGBFwUDQY21hcAAAAogAAACIAAAB/AJaBDNnYXNwAAAOAAAAABQAAAAUAFMAMWdseWYAAANAAAAJ2QAAC9AmqSWiaGVhZAAAAVgAAAAzAAAANg4B/o5oaGVhAAABjAAAACAAAAAkD5gGjmhtdHgAAAIQAAAAdwAAAJxuCAHkbG9jYQAAAxAAAAAwAAAAYB5qIcRtYXhwAAABrAAAABgAAAAgADYARW5hbWUAAA0cAAAAzwAAAWUof1IAcG9zdAAADewAAAATAAAAIP8qAJZ42mNgZGBgAOJVWe0h8fw2Xxm4ORhA4HL+hRAI/Xg5g8i/h+wf2DYCuTwgtQwMAEwIDIQAeNpjYGRgYFvwL47hEwcDgwiDAPsHBqAICpAHAGzPBDl42mNgZGBg0GdwYWBjAAFGBjQAAAxzAHx42mNgZlVlnMDAxsDAOovVmIGB0RhCM89iSGMSYmBgYmRjYGaAAjgDBBSAgMEByFjAOutfGsNZtgWMi4A8RpAcC9A0kBIGVgC/3QoPeNpjYWBIYQACxj8QzDwLiB8DcScDA4sAkO5lYGDSB9LNQH4AkM0EVPcPyAbSTFwMDGyKQHYIUP4TBLMAzWLaAsT7gHgRkK8MFH/IwMDaDlUDtI3pOgMDBwODAoMSgxSQlGMQA7JEGIoYCoA8MzDbDIhlAOIbEksAeNrNkM0NgkAQRt/uIqio4A8IKImlUAgXYxdWQ2I5lqF9jMOCFw9e9SWTmbfZmcMHOIY6Yuhp1Yz3gEb7gilWZ6g5caUT8f96O3sz8pSH3OQyXngTms73+8c76nacLN8ZNh2/JmBCSKRZzJgTaypLViSkrNmwZUdGzp6CkoqDplfz37gXgLgRhnjaY2BgCKMAzmJ4x+jE2MJ4jcmEaQbTK2Yd5grmayx8LGksO1gVWCexvgAAJmsTXHjaTVYNUFTXGb3ffW/f46/IArsLiMj+goZows8uIWZFi8goIcyGiUiJ2RCChNAtIUgJUkOIoWgpIQxDCSUTSpAqE82GUkKtUsYyiRq0xBLDEMahxhpLUdFQSpZ9H71vVzLdO9/jcd+beeeec+75LuFJISFcp6KDcEQkBpJMSIJSqzRqlVqN2WJOiFerQgUxEFShGr0pKTE4KdGk14mCGCI/Ww/s6RoQ9LrNwB4WcsluF52Q4j5avzbp8fyyTalbM8Ki9R9sTzGtj4hKfczf1y8g2dcvOVD0931CVHS4iuIV5rnINVHPZT/6QnZ28WbTc88nZELk7se2K9eEu1dS/Py3+Pv6+1sD/Xb6+voRSqLxrjgpfEwiSDQhIVqzRSGIDCkVgTMYeYUpxmA0xJhDtKBgFyGObsvcDRnpu/hIHHvjLzTvDB7DK9gvHcvJpwQ24Njyq6/gJnoY3h3dKX23i799eTHz3CDOYs5t/ApvXOy5c7TtcP6x7gMfgwKHPrsIO04Q9uOIDr8TbwjHyHoSSzYTIrPFhl4QTTHBIRpBTFBq/39wSrVGjGF3nIZy7BU6TmNxC4wuxCVWVdQkL4aohiEIutAO7VgM06651tLKohpcmOqLiH4my7QDKoCHwsHWdCukQmtwXSXUYi26sZNVI7rFQrz9cMrU066nxH6sCcVBXNT5gZkoSAT+Q2wU9jK2DAxpHHmEEEaSOiHeChYtlfmyaJMYjR6UjEoaCHyIVrWBJrH/k7SKJK2KLzBFLgwm7lb7StWvS3sycum6A9IZWukjIBFy3Z/zAvfLaH0rjv+BQW9fHvEsgRWfisUrzn2hCbbf47MfNNQ5Ls9u3caddydv3Ybhx3+uFN7s7JTmO9nPo+t/xBnhBNEQPSGgVbEh80k9fHo1VjFRBZHNekgWHdJ1mikN4M3HD3am2G/UAm/ayB2SymiUKxkCUrNx3pav3nSfHlx0Y6miCm9fcrTBM3DOergKcZEzZV0469rEna1/vWMKDjFNeRKF98SbzFv6VaZCGAPyYGjMFiYqu/EgkWc8KAxGrYyVWY2BY9ObqFO6zygMgpmjNRebfguvSC9W19E/47w7D+f3/zTSTE3wvPuIognjQbf3HXce1+st/mD7XH//1w3vd5z49VxO2rIrJ4deiY4qbSr8EA63Z0g5jdjRyDCq8V/iLabnBvIweZRYGFcMF5MzSdZPljFItlc4rEJVhgZCjClGEGPM8pySQVcwK5piuKAZm/2lvcXoA7bocOm/rtLK88J9yaY10lo0HFjpVeqffeniVW5aMlBWHB04faN7CF5re/llv1wwc+m7n5ROSbHY47CBH23iwmazM9ynsfq1On9a/2rR/v5POXs1jtXUTJ+53jt5jRCB7Zl/ixuFkz/wm0gek7WWeRU9QI0eZz4BHjPK0pvDgV2JRmvRCuB1pUyzglUoTQXrOi2dOQhv/aQH7wWb7OV2bME5fDP5RGHjVGpmOeR9QtWvSQtPcO9hCzjcUWDHLloBDmyRjsAL2CWctG6Z6louOXgkitbX+hxKw2egD2eG9jnuQD/kx9vzILC5+2n8zOmULjqdzl3E45PQFa14ja0jmhg9OhBQefwZmqCVt5VaE0j12uhwkB1CZPOCjJ9jr4DsXtNJeM81P8rF2uzr1zszH9r+9353A1YaY7ZkQd1lMBs34kc04Zg0kZ0N5djELWGToJwekcKcw0nPX0wL+9uFEiijrnVrD9UCgXx12nYsPG2XuiEaZ+Ty5FP5CohNzCci8ScmQjRKr21lahmRCSq9MlTg9R6+k5QUHuRAuRiJs8tB/LxcGAZCU1MPXjgQFvncL7qvYH1+FhR8I0l0YEXMXepLzxAKXRO82zmLtj+eDW0u9emFHfgFXqvL/WJ5lmEoY169I7xLlCSKKc6UpmKEbFfCyR8kwUp2lXGpOLnFcOYQvVKGk8ifAhMfkLl4K7sK65/dg3GZDqgak8LWJqGLuk4N3L2UmT311NYi4V289BXqMKK95Ay0whVMQdvhBgilP6NHXMP2tyWjWDqCwZ9OnGigH10D3l0tZHcwH0YzH04LbzNc4SSGPETiiZmhS7B49jVTMkHF7iz6kFXOQjXy9klS6tmEWSFvdbVG1hbYy3TIFYunFIFSXiw91OYqBZI4Gss347zUjA1hM43N5j4Y3MfHSc20zDV2tDK/yVGrmMSiRLjMf9k1Ockif3JyzDVLXZJPqYM2tvQdbxlNLqOdDO5UVuy0sG/gdIptzCnNjzFdFcTMMmqcec+X/MiDf52cUqYYo1rDcGk8uanShsOq2iybuHS9BhJ1Fg6Wis4JYd/f8hYuuJmV5VJ8uc+c9uSv7jgmHBPuJo53uysraeQI8XxPt5LA+tx+5qGNZJOXKc2DVFR6/3p6rlqjUD0IbdWDsbpfGY4N7KLj8qRYOik5aIv7Qy5Hyg1SczZuIzVIiZzd3UU7pCJ6Q4rk7EtWhcvTSMahGcv4R7BYKpbvwouOF9CRgoHCgNx8P4MwGPLyQIGUWnC8aIC3lpdjY3l5OQESyjw3z/pyHFNU1shPPpuwAOQT4llK+wHP5qyUSf1gc1LQEs5CxPmc0l071kYd/83lT4LDgK/YYQzAYOXreO9STU7/ty8q8Zv4xPw8GL0JAV/gKN+Cl84vAeEuFLenWKU3cPEdobdBfRD+hN/ixP29vbk7T/716/dN+jo7WGGwAivxJsRCaS2ms15nxm/EMeF3LD22eNWzqFdPDDGrfYZXiAYj86HgbdGcnO2eB2qWJyyNvdMlMN7a0dY/SJvdrOcE1rcP9x9vhtOSDRwQX4aL7Lvzt7DKnAU1V6V2HRflQyFY8OHSpV1LMF6VIt1yVUlZBek0bEjazt87VN1b3cS3gBOz66u7+4465uoqr9f09Zw+V1lVk9kmuc1Wq3lhKb4nvwJasbunIy/rupyHuCLOsd6tZe7YQn7MmJfXI+i1OtaVPEjlRmpmmS3H/OMQbzGDt6uydqWQhfA2MIWFrdoEGs8xTpipr1dHxE6skBnssEoN1kKYy2BHpls+EOlDS2yPbAkI+L6ISwMdp3bPIuaPRhnqbA73GX60F3QQ8OHi8s0zeAdZW4JoxbbY6HFH3wwE4vbW4vp88Llvz80qwQJbTpl0ZXh4AZvxfoQfbavzqwDdjaFTw1dHoPbcZWdNYZf3vBeJ/xRnhT1kDcuyh70nFPGH051FC5zFEw96pdkiqHg56uS1GD2rJ1wQPyTdNcC3LBa6cR5KDFgvpSWfH6AN517cL6CTY4joTtgMiX1XcWAQHbuy4FUWlXsWR9wO2i1lc10jrhqIi+OmIRjvuPdHrGvqyuZ4XPr87Mzkx3N4t7Wjci/UMqj/AwIv4+MAAAB42nWNsWrDMBRFj2MnpVA6deuisRQTZA+BZO+YJS3ZNShBIByQE4jpf/R7e+OK4KV6PN7h6EoPeOKHgtspeFD98UxE5pKXu68mmTnvvGZejL6kqB5lnvnMPBN/ZC55u/tqkpnzxXfmxc3v/PESXfLXg+uGsNn71IdTZ5qltVM2WzeYdl2b1jar2oQunIOLJvnoXe/Z4TlyIeJI4isHUcdAYMNeJtGLT3KGhiVW9Z83bPV60GxZU4/T6nY1clA2cFY77TPjvqh2+sn/AnNQMdoAeNpjYGYAg//qDNMYsAAAKDQBwAAAAQAEAAcACgARAAUAOwAP//8ADwAAAAEAAAAAeNpjYGRgYOBjgAEmBhBfj4ERAAHdAEIAAAEAAAAKABwAHgABREZMVAAIAAQAAAAA//8AAAAAAAB42k2OT07CYBDFf9UKtXwJBdLWBSn/BBSraw5AXLFg4ZrEldG49hScgQN4ANacgVN4i/q+qSEuZubNm3lvhgCIKSgJVs/rFyJCMVQVfhJ8vr+9iqPuNAutRoofnHRLNmz54Isde745cOTEBQ26TLlSzbWdMuJSObdJwq18WoqUB/FtIe9dKCJN625miq7hsXB2Vt/ZHx39PRATGesYqoY8KjvT+ItN+oYnwv6ax4t/mierpXL2531v3rE25mJ6Ujj1Da7FOX2a6KOenDJufgFJpBJIAEhMUEQBAEZDCQAAAFCowklXAAAAAA==) format('truetype');
    font-weight: normal;
    font-style: normal
}
.tc{
    font-family:"extranslate" !important;
    font-size:16px;
    font-style:normal;
    font-feature-settings: "liga" 1;
    font-style: normal;
    text-transform: none;
    font-size: 12px;
    -webkit-font-smoothing: antialiased;
    -webkit-text-stroke-width: 0px;
    -moz-osx-font-smoothing: grayscale;
}
```

仅测试了chrome 火狐未测试
