### ISSUE TITLE
分享一个E站扁平化的样式

### ISSUE THREAD

**Issue by Rinnegan-Naruto** [Mapaler/EhTagTranslator#33]
更新一下，兼容脚本自带的样式
```css
@namespace url(http://www.w3.org/1999/xhtml);

@-moz-document domain("exhentai.org"),domain("e-hentai.org"){
  
  @font-face {
	font-family: 'Material Icons';
	font-style: normal;
	font-weight: 400;
	src: url(https://gapis.geekzu.org/g-fonts/s/materialicons/v31/2fcrYFNaTjcS6g4U3t-Y5ZjZjT5FdEJ140U2DJYC3mY.woff2) format('woff2')
  }
  
  body{background: #eee !important;padding: 0 !important;}
  div,a,p{color: #000 !important;}
  p#nb{background: #00838F !important;height: 32px !important;margin: 0 !important;max-width: 100% !important;}
  p#nb a{color: #fff !important;margin: 0 10px !important;font-size: 16px !important;font-weight: 400 !important;}
  
  p#nb a::before{content: "" !important;font-family: "Material Icons" !important;font-size: 20px !important;position: relative !important;top: 4px !important;}
  p#nb a:nth-of-type(1)::before{content: "\e88a\20" !important;}
  p#nb a:nth-of-type(2)::before{content: "\e2c4\20" !important;}
  p#nb a:nth-of-type(3)::before{content: "\e885\20" !important;}
  p#nb a:nth-of-type(4)::before{content: "\e8b8\20" !important;}
  p#nb a[href*="home"]:nth-of-type(4)::before{content: "\e851\20" !important;}
  p#nb a:nth-of-type(5)::before{content: "\e413\20" !important;}
  
  p#nb a:nth-of-type(6)::before{content: "\e242\20" !important;}
  p#nb a:nth-of-type(7)::before{content: "\e227\20" !important;}
  p#nb a:nth-of-type(8)::before{content: "\e24c\20" !important;}
  p#nb a:nth-of-type(9)::before{content: "\e7fb\20" !important;}
  p#nb a:nth-of-type(10)::before{content: "\e80c\20" !important;}
  p#nb a:nth-of-type(11)::before{content: "\e1bd\20" !important;}
  
  p#nb img{display: none !important;}
  div.ido{background: none !important;border: 0 !important;margin: 0 auto !important;padding: 0px !important;width: 100% !important;max-width: 100% !important;}
  h1.ih{display: none !important;}
  .itc tr{display: inline-table !important;border-collapse: collapse ;margin-top: 10px !important;}
  div#toppane{background: #00BCD4 !important;border: 0 !important;box-shadow: 0 2px 4px #aaa !important;width: auto !important;padding: 10px 0 20px !important;}
  h1.ih{opacity: 0 !important;}
  div.idi{border: 0 !important;margin: 0 !important;padding: 0 !important;width: 100% !important;}
  
  .itc td::after,td.itdc>a::after,#gdc>a::after,.cs3>label::after{content: "" !important;position: absolute !important;z-index: 1 !important;display: block !important;background: none !important;border: 0 !important;border-radius: 3px !important;box-shadow: 2px 2px 5px #00bcd4 !important;color: #000 !important;font-size: 16px !important;font-weight: 400 !important;height: 26px !important;width: 100px !important;line-height: 26px !important;margin-top: -26px !important;}
  .itc td:nth-child(1)::after,td.itdc>a[href*="doujinshi"]::after,#gdc>a[href*="doujinshi"]::after,.cs3>label[for*="doujinshi"]::after{content: "同人志" !important;background: #f40 !important;}
  .itc td:nth-child(2)::after,td.itdc>a[href*="manga"]::after,#gdc>a[href*="manga"]::after,.cs3>label[for*="manga"]::after {content: "漫画" !important;background: #fa4 !important;}
  .itc td:nth-child(3)::after,td.itdc>a[href*="artistcg"]::after,#gdc>a[href*="artistcg"]::after,.cs3>label[for*="artistcg"]::after {content: "同人CG" !important;background: #fe4 !important;}
  .itc td:nth-child(4)::after,td.itdc>a[href*="gamecg"]::after,#gdc>a[href*="gamecg"]::after,.cs3>label[for*="gamecg"]::after {content: "游戏CG" !important;background: #9e4 !important;}
  .itc td:nth-child(5)::after,td.itdc>a[href*="western"]::after,#gdc>a[href*="western"]::after,.cs3>label[for*="western"]::after {content: "欧美" !important;background: #4eb !important;}
  .itc tr+tr td:nth-child(1)::after,td.itdc>a[href*="non-h"]::after,#gdc>a[href*="non-h"]::after,.cs3>label[for*="non-h"]::after {content: "全年龄" !important;background: #4cf !important;}
  .itc tr+tr td:nth-child(2)::after,td.itdc>a[href*="imageset"]::after,#gdc>a[href*="imageset"]::after,.cs3>label[for*="imageset"]::after {content: "图集" !important;background: #c8f !important;}
  .itc tr+tr td:nth-child(3)::after,td.itdc>a[href*="cosplay"]::after,#gdc>a[href*="cosplay"]::after,.cs3>label[for*="cosplay"]::after {content: "角色扮演" !important;background: #d4f !important;}
  .itc tr+tr td:nth-child(4)::after,td.itdc>a[href*="asianporn"]::after,#gdc>a[href*="asianporn"]::after,.cs3>label[for*="asianporn"]::after {content: "亚洲真人" !important;background: #f48 !important;}
  .itc tr+tr td:nth-child(5)::after,td.itdc>a[href*="misc"]::after,#gdc>a[href*="misc"]::after,.cs3>label[for*="misc"]::after {content: "其他" !important;background: #fbb !important;}
  
  
  .ic{height: 26px !important;width: 100px !important;left: 0 !important;position: relative !important;z-index: 2 !important;}
  .ic[src*="_d"]{background: rgba(0,0,0,.3) !important;border-radius: 3px !important;box-shadow: 0 0 0 8px #00BCD4 !important;}
  
  .idi *{color: #000 !important;font-size: 14px !important;font-weight: 400 !important;margin-left: auto !important;}
  .nopm input,select.stdinput{height: 28px !important;margin: 15px 5px 0 !important;}
  .stdinput{background: #eee !important;border-color: #ccc !important;box-sizing: border-box !important;padding: 0 6px !important;}
  option{background: #f7f7f7 !important;}
  .stdbtn{background: #4cf !important;border: none !important;border-radius: 3px!important;padding: 0 15px !important;}
  .itss{width: 50% !important;}
  .itss td{width: 33% !important;}
  
  .itsf{width: auto !important;}
  
  p.ip{color: #333 !important;font-size: 14px !important;display: flex !important;position: absolute !important;padding: 10px 0 0!important;}
  
  table.ptt td,table.ptb td{background: none !important;border: 0 !important;border-radius: 3px !important;color: #235 !important;font-size: 16px !important;display: inline !important;padding: 5px 16px !important;}
  table.ptt td a,table.ptb td a{color: #888 !important;}
  table.ptt td.ptds a,table.ptb td.ptds a,table.ptt td:first-child,table.ptb td:first-child,table.ptt td:last-child a,table.ptb td:last-child a{color: #333 !important;}
  table.ptt td:first-child,table.ptt td:last-child,table.ptb td:first-child,table.ptb td:last-child{background: #4cf !important;box-shadow: 0 2px 6px #ccc !important;margin: 0 10px !important;padding: 5px 10px !important;}
  
  
  table.ptb{margin-top: 20px !important;}
  div.ido>div[style] {margin: 10px auto 20px!important;max-width: 1260px !important;}
  #dmo {color: #333 !important;font-size: 14px !important;top: 0px !important;height: 10px !important;width: auto !important;}
  #dmi{position: relative !important;}
  
  /*div*/.itg{border: 0 !important;margin-top: 17px !important;max-width: 100% !important;width: 100% !important;}

  div.id1{background: #f7f7f7!important;border: 1px solid #ccc !important;border-radius: 3px!important;box-shadow: 0px 2px 3px #888 !important;margin: 5px !important;padding: 5px !important;}
  div.id1:hover{box-shadow: 0px 6px 10px #00000055 !important;transform: translate(0, -5px) !important;transition: all 0.2s ease !important;}
  
  div.id1 *{color: #111!important;font-size: 12px !important;font-weight: 400 !important;line-height: 18px !important;}
  div.id2{height: 36px !important;}
  div.id42{top: 4px !important;}
  
  table.itg{border-radius: 3px !important;box-shadow: 0px 2px 3px #888 !important;}
  table.itg tr{color: #333 !important;}
  table.itg th{background: #f7f7f7 !important;color: #333 !important;}
  tr.gtr0 {background: #f7f7f7 !important;}
  tr.gtr1 {background: #eee !important;}
  table.itg td{border: 0 !important;border-color: #aaa !important;font-size: 14px !important;padding-top: 2px !important;padding-bottom: 2px !important;}
  div.it2{background: #eee !important;border: 0 !important;border-radius: 3px !important;box-shadow: 0px 3px 10px #00000099 !important;padding: 5px !important;}
  div.it5{height: auto !important;}
  td.itdc>a::before{text-align: center !important;height: 24px !important;line-height: 24px !important;width: 80px !important;margin-left: 10px !important;}
  td.itu {border: none !important;}
  
}
 
@-moz-document url-prefix("https://exhentai.org/g/"),url-prefix("https://e-hentai.org/g/"){
  #gdc>a::after {left: -25px !important;}
  div.gm,div#gdt{background: #f7f7f7 !important;border: 0 !important;box-shadow: 0 2px 4px #aaa !important;border-radius: 3px !important;margin-top: 20px !important;padding: 10px !important;}
  div.gm:not([id]){margin-top: 30px !important;}
  div.gm *{color: #333 !important;font-weight: 400 !important;}
  div#gd2,div#gright,div#gmid{background: none !important;}
  h1#gj{border: 0 !important;}
  div#gd4{border-color: #ccc !important;}
  div#taglist div{background: #eee !important;box-shadow: 1px 1px 2px #aaa !important;border-radius: 5px !important;}
  
  #taglist a::after{border-color: #888 !important;box-shadow: 1px 1px 2px #aaa !important;border-top-left-radius: 0 !important;color: #000 !important;left: 0 !important;transform: translate(-1px,21px) !important;}
  
  #taglist a::before{border-color: transparent !important;border: 1px solid transparent !important;margin: -4px -5px ;padding: 3px 4px ;}
  #taglist a:focus::before, #taglist a:hover::before{border-color: #888 !important;border-bottom-color: #eee !important;}
  #taglist .gtl a:after{border-style: dashed !important;}
  #taglist .gtl a:focus::before, #taglist .gtl a:hover::before{border-style: dashed !important;}
  
  .nopm{display: flex !important;}
  input#newtagfield {width: 100% !important; }
  div#gd1 div{border-color: #ccc !important;box-shadow: 2px 2px 5px #aaa !important;}
  .nopm input{margin: 0 !important;}
  
  p.gpc{color: #333 !important;font-size: 14px !important;padding-bottom: 10px !important;}
  .nosel{border-color: rgba(100,100,100,.3) !important;color: #333 !important;font-weight: 400 !important;}
  div.ths{background: #4cf !important;}
  div.tha:hover{background: #4cf !important;}
  
  
  div#gdt img{border-color: #ccc !important;box-shadow: 0px 2px 5px #aaa !important;}
  
  div.c1{border-bottom: 1px #ccc solid !important;}
  div.c1 *{font-size: 14px !important;line-height: 22px !important;}
  div.c2{background: none !important;border: 0 !important;}
  div.c2 *{color: #468 !important;}
  div.c6 a{color: #48c !important;text-decoration:underline !important;}
}

@-moz-document url-prefix("https://exhentai.org/s/"),url-prefix("https://e-hentai.org/s/"){
  div.sni{background: #f7f7f7 !important;border: 0 !important;box-shadow: 0 2px 4px #aaa !important;border-radius: 3px !important;}
  div.sni *{color: #333 !important;font-weight: 400 !important;}
  div.sni h1{padding-top: 10px !important;}
  div.sn a{padding: 0 5px !important;}
  
  div.sn a::before{content: "" !important;font-family: "Material Icons" !important;font-size: 40px !important;display: inline-block ;position: absolute !important;margin-top: -8px !important;height: 0 !important;}
  div.sn a:nth-of-type(1)::before{content: "\e045" !important;background: #00f !important;}
  div.sn a:nth-of-type(2)::before{content: "\e020" !important;}
  div.sn a:nth-of-type(3)::before{content: "\e01f" !important;}
  div.sn a:nth-of-type(4)::before{content: "\e044" !important;}
  
  div.sn a img{opacity: 0 !important;}
}

@-moz-document url("https://exhentai.org/torrents.php"),url("https://e-hentai.org/torrents.php"){
  #torrentform *{color: #333 !important;font-size: 14px !important;font-weight: 400 !important;}
  #torrentform{display: flex !important;justify-content: center !important;margin-bottom: 40px !important;}
  .stdinput,.stdbtn{height: 28px !important;margin: 15px 5px 0 !important;}
  #torrentform p{position: absolute !important;top: 100px !important;}
  table.itg td{padding: 6px !important;}
  table.itg td:first-child{padding-left: 10px !important;}
}

@-moz-document regexp("https:\/\/e.hentai\.org\/.*\.php.*"){
  p#lb{background: #00BCD4 !important;box-shadow: 0 2px 4px #aaa !important;color: transparent !important;font-size: 14px !important;margin: 0 !important;padding: 0 !important;}
  p#lb a{color: #fff !important;display: inline-block !important;height: 40px !important;line-height: 40px !important;border-bottom: 2px solid transparent !important;box-sizing: border-box !important;}
  p#lb a[style]{border-bottom: 2px solid #fff !important;font-weight: 700 !important;}
  .stuffbox{background: #f7f7f7 !important;border: 0 !important;box-shadow: 0 2px 4px #aaa!important;border-radius: 3px!important;padding:10px!important;margin-top: 20px !important;width: 1200px !important;}
  .stuffbox *{color: #333 !important;font-size: 14px !important;line-height: 24px !important;}
  div#namsel {width: auto !important;}
  div#namsel div{width: 90px !important;}
  td.xla{padding: 0 !important;}
  .cs3>label::after{text-align: center !important;margin-left: 10px !important;}
  .cs3>label>img{opacity: 0 !important;}
  td.itu {border: none !important;}
}
@-moz-document url("https://e-hentai.org/news.php"){
  #newsouter{border: 0 !important;}
  .baredge,#botm,.bartop{display: none !important;}
  #newsinner{padding: 0 !important;}
  #nt{color: #333 !important;}
}
@-moz-document url-prefix("https://e-hentai.org/bounty.php"){
  table.itg{box-shadow: none !important;}
  table.itg th:nth-child(1){width: 120px !important;}
  table.itg th:nth-child(5){width: 200px !important;}
  .d3,.d4,.d5{height: auto !important;}
}
```
