### ISSUE TITLE
ETS标签翻译功能讨论

### ISSUE THREAD

**Issue by Mapaler** [Mapaler/EhTagTranslator#50]
https://github.com/seven332/EhViewer/issues/520
想到了补充翻译机制问题。

ETS可以做到有的标签添加跳转到官网的链接
![screenshot 2019-01-30 16 11 25](https://user-images.githubusercontent.com/6565860/51968716-9ccaf680-24ad-11e9-9bb0-d04d8320af74.png)
那么可不可以对没有css翻译的标签做到如下概念图？
![screenshot 2019-01-30 16 11 56](https://user-images.githubusercontent.com/6565860/51968812-d439a300-24ad-11e9-8d6d-4f64a3442d55.png)
自动转换回车和其他需要转义的代码格式，图中我的代码写错了，\A是CSS里才这样写的，正确的应该是\<br\>
这是第一步，减少添加Tag翻译时手动书写代码的麻烦。
<hr>
第二步，是否可以用html5的git，加上一个私钥的资源文件，实现直接在e站新增标签翻译push到wiki？以实现高度简化用户参与翻译成本。

https://github.com/ryanackley/git-html5.js

如果可以实现就不需要要求用户到ETT页面更新数据来增加可能的翻译者了。
当然这部分也可以独立成一个新的程序。

**Comment by OpportunityLiu** [comment]
顶多就上面两个框，你这直接把人吓跑了

**Comment by Mapaler** [comment]
那就默认把下面两个隐藏起来，点击`>更多`展开。主要是也方便我们自己写

**Comment by xioxin** [comment]
通过油猴子编辑wiki本身很难实现
如果需要用户手动复制过来编辑 那么那个ui就毫无意义

**Comment by xioxin** [comment]
我认为应该找到更好的数据存储方式

**Comment by xioxin** [comment]
但是wiki可以提供0成本 免维护 真的很难替代啊

**Comment by Mapaler** [comment]
降低新用户MD学习成本，加快新TAG编辑速度这方面还是有意义的。

**Comment by OpportunityLiu** [comment]
真要这么搞还是得弄个正经数据库

**Comment by OpportunityLiu** [comment]
Azure 上的 F1 档也就够用了
![image](https://user-images.githubusercontent.com/13471233/51986679-b97e2300-24db-11e9-8c75-437638fc8abd.png)

**Comment by Mapaler** [comment]
每天只能运行60分钟吗？

**Comment by OpportunityLiu** [comment]
https://www.reddit.com/r/AZURE/comments/64rr4o/can_someone_explain_what_azure_means_by_cpu/

100% CPU的 60 分钟，感觉怎么都够了

**Comment by Mapaler** [comment]
那怎么具体实现呢？  mysql当数据库，php写页面？还是用什么做后端，前端纯静态代码？

**Comment by OpportunityLiu** [comment]
弄个rest API就好，然后定时刷新到wiki这面，都不需要数据库

**Comment by OpportunityLiu** [comment]
过两天我先写个试下吧

**Comment by Mapaler** [comment]
听不懂了。。

**Comment by OpportunityLiu** [comment]
感觉可以用api直接编辑git啊
https://developer.github.com/v3/git/
我再看看

**Comment by OpportunityLiu** [comment]
先弄了个get的api
https://ehtagconnector.azurewebsites.net/api/database
https://ehtagconnector.azurewebsites.net/api/database/character
https://ehtagconnector.azurewebsites.net/api/database/character/akane%20hino

**Comment by Mapaler** [comment]
等于是自己写了一个git源文件转json吗？
database的没有翻译啊

**Comment by OpportunityLiu** [comment]
是这么设计的，为了防止api被滥用，一次只能获取一类的翻译

用的是这个repo https://github.com/ehtagtranslation/Database

**Comment by Mapaler** [comment]
不能用wiki，必须是主repo吗

**Comment by OpportunityLiu** [comment]
修改的API是
```
POST https://ehtagconnector.azurewebsites.net/api/database/{namespace}?username={username}&email={email}
Content-Type:application/json;
{
    "original": "eng",
    "translated": "chn",
    "introduction": "intro",
    "externalLinks": "links"
}
```

请求内容和数据库里一致是204
添加或修改是 201

**Comment by OpportunityLiu** [comment]
删除API是
```
DELETE https://ehtagconnector.azurewebsites.net/api/database/{namespace}?username={username}&email={email}
Content-Type:application/json;
{
    "original": "eng",
    "translated": "chn",
    "introduction": "intro",
    "externalLinks": "links"
}
```
请求body内容必须和数据库里一致，否则返回 409
成功返回 200

**Comment by OpportunityLiu** [comment]
通过URI query 的用户名和邮箱可以显示提交记录
![image](https://user-images.githubusercontent.com/13471233/52286804-da46ec80-29a3-11e9-8d0d-4db29da04331.png)

**Comment by OpportunityLiu** [comment]
既然api都有了就主repo呗
历史记录比wiki清晰的多

**Comment by Mapaler** [comment]
那干嘛还用md呢？直接json储存不更方便吗

**Comment by OpportunityLiu** [comment]
也是，省的再parse了

**Comment by OpportunityLiu** [comment]
但是json的话 diff 会很难看

**Comment by Mapaler** [comment]
就不要压缩撒，全部格式化展开

**Comment by OpportunityLiu** [comment]
![image](https://user-images.githubusercontent.com/13471233/52287453-26466100-29a5-11e9-910a-b8dbe6b54014.png)
这个只需要用户名和邮箱，也不用api和token啥的

**Comment by Mapaler** [comment]
而且就可以强制规定不同属性的书写格式了，外部连接直接做成数组。就是文字和图片混合的js格式不好制定。

**Comment by OpportunityLiu** [comment]
json你图片啥的咋搞，还是md的格式的话不如继续md
还是别造轮子了

**Comment by Mapaler** [comment]
https://github.com/Mapaler/EhTagTranslator/wiki/%E6%95%B0%E6%8D%AE%E5%BA%93%E5%BC%80%E5%8F%91%E6%96%87%E6%A1%A3

当时我试着搞的，比较麻烦，仅供参考。

**Comment by OpportunityLiu** [comment]
其实也不是不行

Pros
+ 程序处理方便

Cons
+ 兼容问题
+ 预览不方便
+ Diff怎么办？全收起来肯定不行，全展开又太长了点，每个翻译收成一行。。。这程序没法写了

。。。
感觉还是别改了

**Comment by OpportunityLiu** [comment]
还可以搞 GitHub Pages

https://ehtagtranslation.github.io/Database/database/misc

**Comment by Mapaler** [comment]
md可以自动转成html吗？

**Comment by OpportunityLiu** [comment]
是啊，和wiki一个原理，但是这面可以用样式的

**Comment by Mapaler** [comment]
page服务自动转的（即时更新）还是需要第三方工具哦

**Comment by OpportunityLiu** [comment]
自动的

**Comment by Mapaler** [comment]
那还真是棒啊，我一直是自己写html的，都不知道有这个功能

**Comment by OpportunityLiu** [comment]
改了下api，我写个文档吧

**Comment by Mapaler** [comment]
先写文档把标准定一下，再写程序免得走冤枉路吧

**Comment by OpportunityLiu** [comment]
正在写，稍等

**Comment by Mapaler** [comment]
我比较奇怪你春节还有空写代码？不是天天走亲戚吗

**Comment by OpportunityLiu** [comment]
走了啊，刚回来

**Comment by OpportunityLiu** [comment]
https://github.com/ehtagtranslation/EhTagConnector

**Comment by Mapaler** [comment]
C#写的话，能跑的vps不多吧

**Comment by OpportunityLiu** [comment]
为啥？

**Comment by OpportunityLiu** [comment]
C#风评被害

**Comment by Mapaler** [comment]
我买的都是linux的，应该跑不了吧

**Comment by OpportunityLiu** [comment]
你这是偏见，现在这玩意在Linux上跑的更好，可以在openssl的帮助下支持tls1.3，win上都没有这东西。

连powershell都有linux版了

**Comment by OpportunityLiu** [comment]
你要想在自己vps跑就给你写个dockerfile，直接docker里跑

**Comment by Mapaler** [comment]
C#不是需要.Net吗？你写的是Core版的？需要的内存会不会比py、node之类的多呀？

**Comment by Mapaler** [comment]
我已经在跑H@H了，同时跑java和c#还要运行我的网站http+php会不会卡死？:sweat_smile:
docker到底是什么其实我到现在都搞不懂，因为我根本不懂linux。

**Comment by OpportunityLiu** [comment]
h@h主要太费硬盘，我的vps只有10G跑起来太吃力

**Comment by Mapaler** [comment]
我去年年末买的搬瓦工网络星期一特别版，30美元，40G空间。

**Comment by OpportunityLiu** [comment]
https://github.com/ehtagtranslation 总之先加一下组织呗
@mapaler @xioxin

**Comment by OpportunityLiu** [comment]
我也是搬瓦工，可以在我那跑，反正上面啥也没有

**Comment by Mapaler** [comment]
我这几天都碰不到电脑

**Comment by OpportunityLiu** [comment]
你在用手机聊github？

**Comment by Mapaler** [comment]
对啊
![](https://i.imgur.com/EVjRH4V.png)

**Comment by Mapaler** [comment]
这几天碰的全是方向盘，接人送人

**Comment by OpportunityLiu** [comment]
这是啥软件 openhub 一点不好用

**Comment by Mapaler** [comment]
长聊天推荐
https://play.google.com/store/apps/details?id=com.gh4a
能直接到尾端
不过我目前用的界面和功能更好的
https://play.google.com/store/apps/details?id=com.fastaccess.github
就是长聊天要往下翻很多页很麻烦。

**Comment by OpportunityLiu** [comment]
试了下部署到我的vps上，然后直接segment fault 了，debug 也不会 de，可能是我手贱升级了 Ubuntu 19.04 的原因吧

**Comment by xioxin** [comment]
后端为啥不用node.js呐？

**Comment by OpportunityLiu** [comment]
不会

**Comment by xioxin** [comment]
哦

**Comment by OpportunityLiu** [comment]
而且这里面大部分内容都是从之前项目里复制的 https://GitHub.com/opportunityliu/e-viewer

**Comment by Mapaler** [comment]
你们一位是写UWP的用C#，一位是写前端的用node。（而我都不会:joy:）
话说为什么不是php？[滑稽]

**Comment by Mapaler** [comment]
你们一位是写UWP的用C#，一位是写前端的用node。（而我都不会:joy:）
话说为什么不是php？[滑稽]

**Comment by OpportunityLiu** [comment]
C#的git库在Linux上各种爆炸，感觉一时半会是搞不定了，就先在azure的win容器上那么跑着吧

**Comment by OpportunityLiu** [comment]
你们要是没啥问题我就开始往新的repo提交翻译了？ @mapaler @xioxin

**Comment by Mapaler** [comment]
都还没有程序支持这个API吧

**Comment by OpportunityLiu** [comment]
改一下应用里的repo地址就完了啊，数据格式最后没改，提交记录都import过去的。

事实上我也不希望大家用那个的get api，每天就一个小时，还是用来改善提交翻译的体验比较重要，get自己去拉GitHub，和原来一样，不管是拉GitHub渲染好的页面还是raw content都差不多没啥变化吧。

**Comment by Mapaler** [comment]
可是这样普通人就没法用wiki来编辑了吧，普通人的编辑渠道做好没有？而且reademe需要重写。我觉得没有搞好整套前，还是继续用wiki吧。

**Comment by OpportunityLiu** [comment]
加了个 release，把 GET API 删了一部分
https://github.com/ehtagtranslation/Database/releases

**Comment by OpportunityLiu** [comment]
README重写的差不多了
https://github.com/ehtagtranslation/Database/blob/master/README.md
https://github.com/ehtagtranslation/Database/blob/master/LICENSE.md
https://github.com/ehtagtranslation/Database/blob/master/CONTRIBUTING.md

**Comment by Mapaler** [comment]
所以说普通人现在的编辑渠道是什么？

**Comment by OpportunityLiu** [comment]
API啊，等你两了

**Comment by Mapaler** [comment]
ETB应该不会加入的，因为ETB只负责生成css，最后本身是不运行的。一个css是做不了什么的。

**Comment by OpportunityLiu** [comment]
@xioxin 反正调API还是比较容易的，我的应用也可以把这个功能加进去。

最后还有 PR，我都写了

https://github.com/ehtagtranslation/Database/blob/master/CONTRIBUTING.md#%E7%BC%96%E8%BE%91%E6%95%B0%E6%8D%AE%E5%BA%93

**Comment by Mapaler** [comment]
等有空再慢慢搬过去吧

**Comment by Mapaler** [comment]
@OpportunityLiu 你Readme里面那些特殊图片代码在哪里找的

**Comment by OpportunityLiu** [comment]
啥特殊图片，你说 shields.io 的 badge？

API 是不是还是要求一下GitHub第三方登录，只用用户名和邮箱是不是门槛太低了？

**Comment by OpportunityLiu** [comment]
试了下只需要个 user:email 的 scope 就够了

**Comment by Mapaler** [comment]
就是 ![][plat-web] 这种代码就可以生成图片的。

反正我看不懂，我是觉得应该是需要内置修改的项目，来申请一个密钥，或者其他能识别出来源的方式才能用API，否则需要登陆获取通行证。这种能够追朔来源的，才好在出现问题的时候找人或者拒绝请求。不然他的程序给你内容全删掉了你都找不到是谁。

**Comment by OpportunityLiu** [comment]
那就是普通的图片代码啊，看文件最后

**Comment by Mapaler** [comment]
不知道这个写法，还有资源文件的吗？

**Comment by OpportunityLiu** [comment]
就是引用功能啊，最原始的md就可以这么写的

**Comment by xioxin** [comment]
过年时候家里有些事情很忙没怎么看, 你们效率倒是真快 😹 

现在有一些问题 对于编辑,删除api如何防止滥用 能否回滚 用户鉴权等

现在json的数据结构存在一些问题
* Namespace缺少翻译
* 字段key过长导致json体积变大
* 统一风格的key
这是我设想的格式👇
```
{
    "Head": {
        
    },
    "Version": 10,
    "LastUpdateTime": 1549884030,
    "Namespace": [
        {
            "Raw": "female",
            "Name": "女性",
            "Count": 1,
            "Tag": [
                {
                    "Raw": "furry",
                    "Name": "毛绒绒",
                    "Vary": 1, // 上次更新变化 1 新增 2 编辑 0 未变化(未变化推荐删除字段以减少json体积)
                    "Describe": "具有一些人类特征的动物。更偏向动物, 毛绒绒的",
                    "Image": [
                        "https://example.com/example.jpg"
                    ],
                    "Link": [ // 💗 Zelda
                        {"Name": "外部站点连接", "Href": "https://example.com"},
                        {"Name": "外部站点连接", "Href": "https://example.com"}
                    ]
                }
            ]
        }
    ]
}
```



每次修改都会自动发布版本 还是 有时间间隔

**Comment by xioxin** [comment]
我写先一个编辑器吧

可能用到的接口
* 获取列表
* 获取tag详细内容
* 新增/编辑/删除

关于油猴子插件 我不再打算维护旧的了 因为吧angular.js 弄到猴子里真是个愚蠢的行为 各种不兼容
但是离开了mvvm框架根本不想写ui啊 😂

**Comment by Mapaler** [comment]
@xioxin 用原生写吧:stuck_out_tongue_winking_eye:

**Comment by xioxin** [comment]
@Mapaler 这么艰巨的任务还是你来吧 :joy:

**Comment by Mapaler** [comment]
你也可以考虑写成扩展，不过能不能通过审核就是另一回事了。
用脚本的话，能在e站编辑，就不需要直接往项目导流了，所以UI全部写在E站应该会简单些。
另外把快速复制缩略图的功能可以考虑合并进去。（打开翻译工具开关时就显示复制按钮）
或者使用unix模式tag翻译、ui翻译、bt下载、翻译工具，分开各为一个脚本。
新脚本的namespace注意写成组织，不要继续用我的主页了。

**Comment by xioxin** [comment]
我现在本身工作很忙 也经常加班 所以不要太指望我能比较快的搞定

**Comment by Mapaler** [comment]
大家都忙，我也在加班，目前完全没时间搞。

**Comment by OpportunityLiu** [comment]
https://github.com/ehtagtranslation/Database/releases
现在每次都是全量发布啊，也没多大，压缩啥的就交给gz和brotli吧

**Comment by xioxin** [comment]
https://ehtagtranslation.github.io/Editor/#/list/artist

**Comment by xioxin** [comment]
有api的文档吗?

**Comment by OpportunityLiu** [comment]
https://github.com/ehtagtranslation/Database#%E5%BC%80%E5%8F%91%E8%80%85
https://github.com/ehtagtranslation/EhTagConnector

不过我正在加认证，API还在改

**Comment by OpportunityLiu** [comment]
大概可以了，用github token认证

**Comment by Mapaler** [comment]
现在是只要数据库发生一次修改就会生成一个Release吗？感觉会多爆啊。而且每次生成都需要API后端计算的吧？感觉还是过一段时间生成一个比较科学。
如果用Release后，那么ETB生成JSON的功能是不是就不需要了？

**Comment by OpportunityLiu** [comment]
还行吧，反正一次也就1M，不生成难道后端api就不计算了？提交git一样要算一遍

**Comment by Mapaler** [comment]
我说的是将来Release的数量会多爆，翻页不是翻死人吗？

API提交修改的请求可不可以提交多个？这样在编辑器先暂时本地储存，然后再一起提交上去，减少Release数量。

**Comment by OpportunityLiu** [comment]
https://github.com/ehtagtranslation/Database/releases/latest 不就是最新的

~~一次提交多个可以有，我再改改吧~~

**Comment by OpportunityLiu** [comment]
不过那样空中碰撞会很麻烦呀

release数量多就多呗， CI不就是这样

**Comment by OpportunityLiu** [comment]
没事干翻release干啥，那无论如何commit还能翻死人

**Comment by OpportunityLiu** [comment]
https://github.com/ehtagtranslation/Database/releases/tag/commit-af319919c8c3f0cdd08a469ebfa1a02df3f87763

![default](https://user-images.githubusercontent.com/13471233/52577085-59cd3380-2e5c-11e9-858d-7f4e2ab864ef.png)
压缩了一下，更小了

**Comment by Mapaler** [comment]
web的没法用gz吧，本地程序感觉也不差那点流量，应该会直接下json。如果两个人同时编辑，会出现什么效果？

**Comment by OpportunityLiu** [comment]
> 
> 
> 过年时候家里有些事情很忙没怎么看, 你们效率倒是真快 😹
> 
> 现在有一些问题 对于编辑,删除api如何防止滥用 能否回滚 用户鉴权等
+ 鉴权使用 github 的鉴权，每个提交都会和某个github user 对应
  https://github.com/ehtagtranslation/EhTagConnector#%E7%94%A8%E6%88%B7%E8%AE%A4%E8%AF%81
+ 回滚直接 git revert，和之前是一样的
> 
> 现在json的数据结构存在一些问题
> 
>     * Namespace缺少翻译
加上了
>     * 字段key过长导致json体积变大
gzip以后没啥区别，见上条，一样的内容压缩起来非常高效
>     * 统一风格的key
你们js不是喜欢camalCase吗，我这里是serializer自动转的camalCase，aspnet的默认设置，我的这面命名都是PascalCase
>       这是我设想的格式👇
> 
> 
> ```
> {
>     "Head": {
>         
>     },
>     "Version": 10,
>     "LastUpdateTime": 1549884030,
>     "Namespace": [
>         {
>             "Raw": "female",
>             "Name": "女性",
>             "Count": 1,
>             "Tag": [
>                 {
>                     "Raw": "furry",
>                     "Name": "毛绒绒",
>                     "Vary": 1, // 上次更新变化 1 新增 2 编辑 0 未变化(未变化推荐删除字段以减少json体积)
>                     "Describe": "具有一些人类特征的动物。更偏向动物, 毛绒绒的",
>                     "Image": [
>                         "https://example.com/example.jpg"
>                     ],
>                     "Link": [ // 💗 Zelda
>                         {"Name": "外部站点连接", "Href": "https://example.com"},
>                         {"Name": "外部站点连接", "Href": "https://example.com"}
>                     ]
>                 }
>             ]
>         }
>     ]
> }
> ```
> 
> 每次修改都会自动发布版本 还是 有时间间隔

最多也就10秒钟新版本就发布了，每次修改通过 webhook 触发

**Comment by OpportunityLiu** [comment]
> 如果两个人同时编辑，会出现什么效果？

https://github.com/ehtagtranslation/EhTagConnector#%E7%89%88%E6%9C%AC%E6%8E%A7%E5%88%B6

后发的那个会被412退回来

**Comment by xioxin** [comment]
关于鉴权 最好是添加新标签可以不登录, 编辑和删除需要登陆

**Comment by Mapaler** [comment]
添加新标签可以不登录，也可以登录来记录贡献？
要不要每隔一段时间统计一下这段时期的修改行数？

**Comment by OpportunityLiu** [comment]
还是别放宽了，连github都懒得注册的翻译质量真能不敢恭维

字段名字改短了，不过我觉得用处不大
```jsonc
{
    "raw": "gotoubun no hanayome",
    "name": "五等分的新娘",
    "intro": "《五等分的新娘》（日语：五等分の花嫁）是由日本漫画家春场葱所创作的少年漫画作品。于《周刊少年Magazine》2017年第36・37合并号开始正式连载中。 ",
    "links": "[维基百科](https://zh.wikipedia.org/zh-cn/五等分的新娘) (*)"
}
```

**Comment by OpportunityLiu** [comment]
![default](https://user-images.githubusercontent.com/13471233/52581518-ed573200-2e65-11e9-8884-17b592c7d532.png)
果然没省多少，没压缩的省了200k，压缩的只减少了6k

**Comment by xioxin** [comment]
有点门槛是好的

**Comment by OpportunityLiu** [comment]
有鉴权好歹可以ban用户，然后依赖github的anti-rebuse机制，不然真的有可能被整死啊

**Comment by xioxin** [comment]
我明天写个脚本 吧图片和外部地址解析出来 方便使用

**Comment by xioxin** [comment]
![image](https://user-images.githubusercontent.com/5716100/52582352-f6490300-2e67-11e9-8cf0-1141b59ca79c.png)
为啥有些小写 有些大写

**Comment by OpportunityLiu** [comment]
序列化器弄错了，等我改下

**Comment by OpportunityLiu** [comment]
修好了
ehtagtranslation/EhTagConnector@df9c0d5

**Comment by xioxin** [comment]
![image](https://user-images.githubusercontent.com/5716100/52587328-c0f6e200-2e74-11e9-9497-366b0dedda2f.png)
![image](https://user-images.githubusercontent.com/5716100/52587371-d2d88500-2e74-11e9-8604-d912216f1d9a.png)
花了一晚上的时间 整理电脑里的所有漫画 😂  有好多重复的

**Comment by seven332** [comment]
建议收集未翻译的标签。

**Comment by OpportunityLiu** [comment]
这个项目也可以迁移过去，github会自动帮你301的 @Mapaler 
然后这个项目里数据库使用的那些issue也可以移动到 https://github.com/ehtagtranslation/Database

**Comment by OpportunityLiu** [comment]
@seven332 https://e-hentai.org/tools.php?act=taggroup 这里就能扒到足够多的了，我的那个客户端的自动完成一部分也是用的这里的数据，然后要干啥呢？

**Comment by seven332** [comment]
可以生成标签翻译优先级。

**Comment by seven332** [comment]
而且那里的标签不全。

**Comment by xioxin** [comment]
@OpportunityLiu 这个项目可以不迁移进去 肯定是要重写的

**Comment by OpportunityLiu** [comment]
star可是重要财产，说丢就丢啊

改成用 appveyor 发布了
https://ci.appveyor.com/project/EhTagApi-Bot/database

**Comment by Mapaler** [comment]
那个又是什么。为什么打包用的gz而不是zip呢？前端解压gz不方便吧。

**Comment by xioxin** [comment]
前段根本不可能用压缩格式的

**Comment by OpportunityLiu** [comment]
前端只能用js的那个，json 和 gz 都没啥用
![default](https://user-images.githubusercontent.com/13471233/52620245-ffc18200-2ede-11e9-881b-fe1f99ee219b.png)

解压的话反正都要引入新依赖，zip和gz差不多

**Comment by OpportunityLiu** [comment]
@Mapaler 总之就是发布换到另一个独立的服务了

这样 azure 配额超掉只影响修改的 api，发新版本不受影响

**Comment by OpportunityLiu** [comment]
浏览器大概只能这么搞
![default](https://user-images.githubusercontent.com/13471233/52621558-93488200-2ee2-11e9-8b55-cd63dcbd1ae8.png)

**Comment by xioxin** [comment]
这种方法叫jsonp

**Comment by OpportunityLiu** [comment]
对。。。话说最后一行花了我30s

**Comment by Mapaler** [comment]
我都看不懂这些代码，ES6以上的都不懂。😂

**Comment by xioxin** [comment]
> Failed to load https://ehtagconnector.azurewebsites.net/api/database: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.


需要跨域白名单

localhost:4200 ehtagtranslation.github.io exhentai.org e-hentai.org

**Comment by OpportunityLiu** [comment]
应该可以了，为了跨域方便把认证的请求头换了一下

https://github.com/ehtagtranslation/EhTagConnector#%E7%94%A8%E6%88%B7%E8%AE%A4%E8%AF%81

![default](https://user-images.githubusercontent.com/13471233/52717240-a3905800-2fdb-11e9-80f9-51067af491e1.png)

**Comment by OpportunityLiu** [comment]
不过准备把markdon解析加上了，API还要改

**Comment by OpportunityLiu** [comment]
差不多改好了

**Comment by OpportunityLiu** [comment]
https://ehtagconnector.azurewebsites.net/api/database/parody/touhou%20project

```yaml
{
  "name": {
    "raw": "![阴阳玉](http://ww1.sinaimg.cn/large/6c84b2d6gw1f41mmp72jbg200c00c0ex.gif)东方Project⛩",
    "text": "东方Project⛩",
    "html": "<p><img src=\"http://ww1.sinaimg.cn/large/6c84b2d6gw1f41mmp72jbg200c00c0ex.gif\" alt=\"阴阳玉\" />东方Project⛩</p>",
    "ast": [
      {
        "type": "paragraph",
        "content": [
          {
            "type": "image",
            "title": "",
            "url": "http://ww1.sinaimg.cn/large/6c84b2d6gw1f41mmp72jbg200c00c0ex.gif",
            "nsfw": false,
            "content": [
              {
                "type": "text",
                "text": "阴阳玉"
              }
            ]
          },
          {
            "type": "text",
            "text": "东方Project⛩"
          }
        ]
      }
    ]
  },
  "intro": {
    "raw": "![囧仙子1](http://ww2.sinaimg.cn/large/6c84b2d6gw1f36161k7odj205k06ydg1.jpg)\n捐一串还是两串都可以哦～\n![囧仙子头像](http://ww3.sinaimg.cn/large/6c84b2d6gw1f3tth5q2l9j2032032mx2.jpg)\n跟瓦格哇我噶哇嘎嘎\n![囧仙子2](http://ww3.sinaimg.cn/large/6c84b2d6gw1f3ttfmlq2ij2046093aa9.jpg)",
    "text": "捐一串还是两串都可以哦～\n跟瓦格哇我噶哇嘎嘎",
    "html": "<p><img src=\"http://ww2.sinaimg.cn/large/6c84b2d6gw1f36161k7odj205k06ydg1.jpg\" alt=\"囧仙子1\" /><br />\n捐一串还是两串都可以哦～<br />\n<img src=\"http://ww3.sinaimg.cn/large/6c84b2d6gw1f3tth5q2l9j2032032mx2.jpg\" alt=\"囧仙子头像\" /><br />\n跟瓦格哇我噶哇嘎嘎<br />\n<img src=\"http://ww3.sinaimg.cn/large/6c84b2d6gw1f3ttfmlq2ij2046093aa9.jpg\" alt=\"囧仙子2\" /></p>",
    "ast": [
      {
        "type": "paragraph",
        "content": [
          {
            "type": "image",
            "title": "",
            "url": "http://ww2.sinaimg.cn/large/6c84b2d6gw1f36161k7odj205k06ydg1.jpg",
            "nsfw": false,
            "content": [
              {
                "type": "text",
                "text": "囧仙子1"
              }
            ]
          },
          {
            "type": "br"
          },
          {
            "type": "text",
            "text": "捐一串还是两串都可以哦～"
          },
          {
            "type": "br"
          },
          {
            "type": "image",
            "title": "",
            "url": "http://ww3.sinaimg.cn/large/6c84b2d6gw1f3tth5q2l9j2032032mx2.jpg",
            "nsfw": false,
            "content": [
              {
                "type": "text",
                "text": "囧仙子头像"
              }
            ]
          },
          {
            "type": "br"
          },
          {
            "type": "text",
            "text": "跟瓦格哇我噶哇嘎嘎"
          },
          {
            "type": "br"
          },
          {
            "type": "image",
            "title": "",
            "url": "http://ww3.sinaimg.cn/large/6c84b2d6gw1f3ttfmlq2ij2046093aa9.jpg",
            "nsfw": false,
            "content": [
              {
                "type": "text",
                "text": "囧仙子2"
              }
            ]
          }
        ]
      }
    ]
  },
  "links": {
    "raw": "",
    "text": "",
    "html": "",
    "ast": []
  }
}
```

**Comment by xioxin** [comment]
数据要使用在多种不同的平台语言以及ui环境，富文本会增加解析使用的难度

我觉得应该简化格式 没必要追求与之前的完全兼容
* 描述与图片分离，描述本身应该言简意赅，与图片混编的意义不大
* 描述中的换行统一使用换行符 `\n` 避免出现 `<br>`

**Comment by Mapaler** [comment]
我觉得api应该加上格式参数，根据不同需求返回不同类型的内容，没必要放在一个json里。

**Comment by Mapaler** [comment]
图片只需要简化为 src 和 alt 就行了，写在title的url自动转换为src就行了）

**Comment by OpportunityLiu** [comment]
富文本用不用、怎么用是下游的事情，我只是按md标准吧把内容全解析了

**Comment by OpportunityLiu** [comment]
br那个没弄懂你的意思，渲染成纯文本自然是\n，渲染成HTML自然是br，在AST里肯定是个独立的token

**Comment by OpportunityLiu** [comment]
格式参数是应该有的

**Comment by OpportunityLiu** [comment]
图片问题一样，HTML处理不了content里的富文本只能转成纯文本丢在ALT里，但是AST应该保留全部的信息

**Comment by Mapaler** [comment]
富文本只能用在网页里吧，感觉用处不多啊。js分解模式的图片我觉得这样就够了，因为写数据库的时候有前置规定，不会出现其他异常吧。出现了也可以强制解析成这样。
```js
          {
            "type": "img",
            "alt": "囧仙子头像",
            "url": "http://ww3.sinaimg.cn/large/6c84b2d6gw1f3tth5q2l9j2032032mx2.jpg",
            "nsfw": 0
          },
```

**Comment by OpportunityLiu** [comment]
```yaml
{
  "name": {
    "raw": "正太",
    "text": "正太",
    "html": "<p>正太</p>",
    "ast": [
      {
        "type": "paragraph",
        "content": [
          {
            "type": "text",
            "text": "正太"
          }
        ]
      }
    ]
  },
  "intro": {
    "raw": "小男孩。\n![举例](# \"https://exhentai.org/t/8d/e4/8de4084018d6fd26f7fb8843dfdba5949835ac02-219707-1128-1600-jpg_l.jpg\")![图](# \"https://exhentai.org/t/b4/f2/b4f27457519a0eb55cbc231c34152084d8351cd3-543154-1000-1458-jpg_l.jpg\")![图](# \"https://exhentai.org/t/3a/46/3a466e7dc00e27d80e8d6be4674b08c6b8efb25f-304032-1067-1514-jpg_l.jpg\")",
    "text": "小男孩。",
    "html": "<p>小男孩。<br />\n<img src=\"https://exhentai.org/t/8d/e4/8de4084018d6fd26f7fb8843dfdba5949835ac02-219707-1128-1600-jpg_l.jpg\" alt=\"举例\" nsfw /><img src=\"https://exhentai.org/t/b4/f2/b4f27457519a0eb55cbc231c34152084d8351cd3-543154-1000-1458-jpg_l.jpg\" alt=\"图\" nsfw /><img src=\"https://exhentai.org/t/3a/46/3a466e7dc00e27d80e8d6be4674b08c6b8efb25f-304032-1067-1514-jpg_l.jpg\" alt=\"图\" nsfw /></p>",
    "ast": [
      {
        "type": "paragraph",
        "content": [
          {
            "type": "text",
            "text": "小男孩。"
          },
          {
            "type": "br"
          },
          {
            "type": "image",
            "title": "",
            "url": "https://exhentai.org/t/8d/e4/8de4084018d6fd26f7fb8843dfdba5949835ac02-219707-1128-1600-jpg_l.jpg",
            "nsfw": true,
            "content": [
              {
                "type": "text",
                "text": "举例"
              }
            ]
          },
          {
            "type": "image",
            "title": "",
            "url": "https://exhentai.org/t/b4/f2/b4f27457519a0eb55cbc231c34152084d8351cd3-543154-1000-1458-jpg_l.jpg",
            "nsfw": true,
            "content": [
              {
                "type": "text",
                "text": "图"
              }
            ]
          },
          {
            "type": "image",
            "title": "",
            "url": "https://exhentai.org/t/3a/46/3a466e7dc00e27d80e8d6be4674b08c6b8efb25f-304032-1067-1514-jpg_l.jpg",
            "nsfw": true,
            "content": [
              {
                "type": "text",
                "text": "图"
              }
            ]
          }
        ]
      }
    ]
  },
  "links": {
    "raw": "",
    "text": "",
    "html": "",
    "ast": []
  }
}
```
