### ISSUE TITLE
样式分享

### ISSUE THREAD

**Issue by xioxin** [Mapaler/EhTagTranslator#9]
## 预览

| 里 | 表 |
| --- | --- |
| ![image](https://cloud.githubusercontent.com/assets/5716100/15541389/d03509d2-22be-11e6-96f9-c4f6245bf0e4.png) | ![image](https://cloud.githubusercontent.com/assets/5716100/15541398/deade98e-22be-11e6-8dc2-d0bdb56e5429.png) |
## 表里通用样式

``` css
div#taglist {
    overflow: visible;
    min-height: 295px;
    height: auto;
}
div#gmid {
    min-height: 330px;
    height:auto;
    position: static;
}
#taglist a{
  background:inherit;
}
#taglist a::before{
    font-size:12px;
    overflow: hidden;
    line-height: 20px;
    height: 20px;
}
#taglist a::after{
    display: block;
    color:#FF8E8E;
    font-size:14px;
    background: inherit;
    border: 1px solid #000;
    border-radius:5px;
    position:absolute;
    float: left;
    z-index:999;
    padding:8px;
    box-shadow: 3px 3px 10px #000;
    min-width:150px;
    max-width:500px;
    white-space:pre-wrap;
    opacity: 0;
    transition: opacity 0.2s;
    transform: translate(-50%,20px);
    top:0;
    left: 50%;
    pointer-events:none;
    padding-top: 8px;
    font-weight: 400;
    line-height: 20px;
}
#taglist a:hover::after,#taglist a:focus::after{
    opacity: 1;
    pointer-events:auto;
}
#taglist a:focus::before,
#taglist a:hover::before {
    font-size: 12px;
    position: relative;
    background-color: inherit;
    border: 1px solid #000;
    border-width: 1px 1px 0 1px;
    margin: -4px -5px;
    padding: 3px 4px;
    color:inherit;
    border-radius: 5px 5px 0 0;
}
div.gt,
div.gtw,
div.gtl{
    line-height: 20px;
    height: 20px;
}

#taglist a:hover::after{ z-index: 9999998; }
#taglist a:focus::after { z-index: 9999996; }
#taglist a:hover::before{ z-index: 9999999; }
#taglist a:focus::before { z-index: 9999997; }
```
## 表站样式

``` css
#taglist a::after{ color:#000; }
```
## 里站样式

``` css
#taglist a::after{ color:#fff; }
```

**Comment by Mapaler** [comment]
感觉很厉害，回去试试，一直不知道怎么解决after显示在外面又能位置随标签变化的方法。

**Comment by xioxin** [comment]
我的解决办法是吧标签外面的滚动条去掉 :joy:

**Comment by Mapaler** [comment]
``` css
 #taglist a{
    background:inherit;
  }
  #taglist a::after{
    background:inherit;
  }
```

明天改成这两个，就可以让表站背景色一致了。另外边框颜色也可以继承。

**Comment by Mapaler** [comment]
看起来你就是让超长的Tag全部铺出来。这样效果也不错。

另外你最好别让a变，而是让上一层的div变
![](http://ww3.sinaimg.cn/large/6c84b2d6jw1f46x1ldf8ej20740400te.jpg)

**Comment by xioxin** [comment]
更新了下样式 直接编辑的顶楼 修改了大小挡住了上一层的div 
尝试在背景中使用继承 结果变成透明了

**Comment by xioxin** [comment]
![image](https://cloud.githubusercontent.com/assets/5716100/15511129/de948c6c-220c-11e6-9c60-9fd95090e0f0.png)

**Comment by Mapaler** [comment]
需要a继承div，然后a::after再继承a

**Comment by Mapaler** [comment]
你为什么不改成div来显示，要用a::before来显示呢？

**Comment by xioxin** [comment]
上面标题要和下面介绍连成一体 所以before要挡在after上 遮挡住部分上边线
子父级关系无法做到这个效果

样式有更新了一下 刚刚的更新貌似不小心复制错误了

**Comment by xioxin** [comment]
刚刚又不小心复制了个错误的版本 这次真的是最新的了

**Comment by Mapaler** [comment]
刚想说你这个问题，然而碰上没有简介的呢。
![](http://ww2.sinaimg.cn/large/6c84b2d6jw1f46y0qjrenj206z03pwep.jpg)

``` css
div#taglist {
    overflow: visible;
    min-height: 295px;
    height: auto;
}
div#gmid {
    min-height: 330px;
    height:auto;
    position: static;
}
#taglist a{
  background:inherit;
}
#taglist a::before{
    font-size:12px;
    overflow: hidden;
    line-height: 20px;
    height: 20px;
}
#taglist a::after{
    display: block;
    color:inherit;
    font-size:14px;
    background: inherit;
    border: 1px solid #000;
    border-radius:5px;
    position:absolute;
    float: left;
    z-index:999;
    padding:8px;
    box-shadow: 3px 3px 10px #000;
    min-width:150px;
    max-width:260px;
    white-space:pre-wrap;
    opacity: 0;
    transition: opacity 0.2s;
    transform: translate(-50%,20px);
    top:0;
    left: 50%;
    pointer-events:none;
    padding-top: 8px;
    font-weight: 400;
    line-height: 20px;
}
#taglist a:hover::after,#taglist a:focus::after{
    opacity: 1;
    pointer-events:auto;
}
#taglist a:focus::before,
#taglist a:hover::before {
    font-size: 12px;
    position: relative;
    background-color: inherit;
    border: 1px solid #000;
    border-color: #000 #000 #666 #000;
    margin: -4px -5px;
    padding: 3px 4px;
    color: inherit;
    border-radius: 5px 5px 0 0;
}
div.gt,
div.gtw,
div.gtl{
    line-height: 20px;
    height: 20px;
}

#taglist a:hover::after{
    z-index: 9999998;
}
#taglist a:hover::before{
    z-index: 9999999;
}

#taglist a:focus::after {
    z-index: 9999996;
}
#taglist a:focus::before {
    z-index: 9999997;
}
```

把背景继承添加上去，表站里站就效果和整体一致了，但是focus的时候也会变成蓝色。你看看可不可以改进一下。
